### PR TITLE
Add STM8S003F3U6TR

### PR DESCRIPTION
**Pull request by fruchti**
Adds the required padstacks for the UFQFPN20 package as well.

### CODE REVIEW

**Comment by carrotIndustries** [comment]
Looks got to me overall, some minor nitpicks:
 - The NRST pin is low active, so add the inverted decoration to the symbol pin
 - The package is missing the parameter program for adjusting the courtyard

**Comment by fruchti** [comment]
Thanks for the feedback. I added the courtyard parameter program and moved the padstacks to the package directory. I did not add the inverted decoration, because that would be a double inversion in my opinion (it seems ST consistently uses a capital N for active-low pins).

**Comment by fruchti** [comment]
Fixed the folder name typo as well. Wasn't aware this was as easy as moving files and deleting pool.db.

**Comment by carrotIndustries** [comment]
In fact, you don't even have to delete the `pool.db` just click 'update pool' in the pool manager to rebuild the database. The courtyard still isn't quite right: https://github.com/carrotIndustries/horizon/wiki/Creating-a-Package#courtyard 

>  At 0mm courtyard expansion the courtyard outline is the (rectangular) hull around copper pads and package outline.

**Comment by fruchti** [comment]
Thanks! Should be all fixed now.

**Pull request merged**
